services:
  - type: web
    name: frontend-backend-node
    env: node
    rootDir: backend-nodejs
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: your-mongodb-uri

  - type: web
    name: yolo-python-api
    env: python
    rootDir: yolo-python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
