services:
  - type: web
    name: frontend-backend-node
    env: node
    rootDir: backend-nodejs
    buildCommand: |
      npm install
      pip install -r ../yolo-python/requirements.txt
    startCommand: "node app.js"
    envVars:
      - key: PORT
        value: 3000
